// SPDX-License-Identifier: GPL-3.0-or-later
// Actual App AST callbacks/JSX bindings and compiled Monitor, controlled events only.
import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';
import {collect} from './timeline-harness.mjs';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),build=process.env.MONO_CUT_PREVIEW_TEST_BUILD,require=createRequire(join(root,'package.json')),ts=require('typescript');
const source=ts.createSourceFile('App.tsx',readFileSync(join(root,'src/App.tsx'),'utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
function find(node,predicate){if(predicate(node))return node;let found;ts.forEachChild(node,child=>{if(!found)found=find(child,predicate);});return found;}
const app=find(source,n=>ts.isFunctionDeclaration(n)&&n.name?.text==='App');
const declaration=name=>find(source,n=>ts.isVariableDeclaration(n)&&n.name.getText(source)===name);
const fn=name=>find(app,n=>ts.isFunctionDeclaration(n)&&n.name?.text===name).getText(source);
const hook=name=>declaration(name).initializer.arguments[0].getText(source);
const effect=find(app,n=>ts.isCallExpression(n)&&n.expression.getText(source)==='useEffect'&&n.arguments[0].getText(source).includes("document.addEventListener('keydown', key)")).arguments[0].getText(source);
const monitors={};ts.forEachChild(app,function visit(node){if(ts.isJsxSelfClosingElement(node)&&node.tagName.getText(source)==='Monitor'){const title=node.attributes.properties.find(p=>p.name?.text==='title').initializer.text;monitors[title.toLowerCase()]=node;}ts.forEachChild(node,visit);});
const monitored=['title','active','onActivate','markable','playable','onPlay','onPause','onStep','onMarkIn','onMarkOut','fps','frame','duration','src','status','image','audio','setFrame','videoRef','speed','onSeek'];
const attrs=node=>'{'+node.attributes.properties.filter(p=>monitored.includes(p.name?.text)).map(p=>`${p.name.text}: ${!p.initializer?'true':ts.isJsxExpression(p.initializer)?p.initializer.expression.getText(source):p.initializer.getText(source)}`).join(',')+'}';
const modeNode=find(app,n=>ts.isJsxOpeningElement(n)&&n.tagName.getText(source)==='select'&&n.attributes.properties.some(p=>p.name?.text==='aria-label'&&p.initializer?.text==='Editor mode'));
const modeChange=modeNode.attributes.properties.find(p=>p.name?.text==='onChange').initializer.expression.getText(source);
const tabs=[];ts.forEachChild(app,function visit(node){if(ts.isJsxOpeningElement(node)&&node.tagName.getText(source)==='button'&&node.attributes.properties.some(p=>p.name?.text==='role'&&p.initializer?.text==='tab'))tabs.push(node.attributes.properties.find(p=>p.name?.text==='onClick').initializer.expression.getText(source));ts.forEachChild(node,visit);});
const compile=text=>ts.transpileModule(text,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
const actualApp=compile([find(source,n=>ts.isFunctionDeclaration(n)&&n.name?.text==='normalizeKey').getText(source),`const defaults=${declaration('defaults').initializer.getText(source)};`,fn('sourceIdentity'),fn('navigateMonitorTabs'),fn('sourceCommandsReady'),fn('activateWorkspace'),fn('changeMode'),fn('resetSourceForProject'),fn('selectSource'),`const activateMonitor=${hook('activateMonitor')}; const stepSource=${hook('stepSource')}; const replaceProject=${hook('replaceProject')}; const markRange=${declaration('markRange').initializer.getText(source)};`, `globalThis.actual={install:${effect},activateMonitor,activateWorkspace,changeMode,sourceIdentity,navigateMonitorTabs,resetSourceForProject,selectSource,replaceProject,stepSource,defaults,modeChange:${modeChange},tabs:[${tabs}],props:()=>({source:${attrs(monitors.source)},program:${attrs(monitors.program)}})};`].join('\n'));
class Target {
  getAttribute(name){return this.attrs[name]??null;}
  constructor(tag='div',attrs={},parent=null){this.tag=tag;this.attrs=attrs;this.parent=parent;}
  closest(selectors){for(let node=this;node;node=node.parent)for(const selector of selectors.split(',')){
    if(selector==='[contenteditable]:not([contenteditable="false"])'){if('contenteditable'in node.attrs&&node.attrs.contenteditable!=='false')return node;continue;}
    if(selector.startsWith('.')){if(node.attrs.class?.split(' ').includes(selector.slice(1)))return node;continue;}
    const tag=selector.match(/^[a-z]+/)?.[0];if(tag&&node.tag!==tag)continue;
    const attr=selector.match(/\[([^=\]]+)(?:="([^"]*)")?\]/);if(attr&&(!(attr[1]in node.attrs)||(attr[2]!==undefined&&node.attrs[attr[1]]!==attr[2])))continue;
    if(tag||attr)return node;
  }return null;}
}
const plain=x=>JSON.parse(JSON.stringify(x)),r=(num,den=1)=>({num,den});
function harness(mode='advanced'){
  const events=[],listeners=new Set(),media={id:'m',path:'synthetic.mov',kind:'video',missing:false,name:'Source',fps:r(24000,1001),duration:r(16)},project={id:'p',fps:r(30),in_point:10,out_point:200,media:[media],clips:[]};
  const s={exports:{},Element:Target,mode,monitorTab:'program',monitorTarget:'program',monitorTargetRef:{current:'program'},project,projectRef:{current:project},sourceSelection:{current:{projectId:'p',id:'m',path:media.path,kind:media.kind}},sourceId:'m',sourcePath:'asset://source',sourceBusy:false,sourceFrame:42,sourceFrameRef:{current:42},sourceIn:0,sourceOut:null,frame:120,frameRef:{current:120},previewPath:'asset://program',previewDirty:false,previewPlayable:true,sourceShuttle:0,shuttle:0,sourceVideo:{current:{paused:true,currentTime:0}},programVideo:{current:{paused:true,currentTime:0}},modal:null,recordShortcut:null,selected:[],sourceGeneration:{current:0},sourceAsset:{current:null},sourceIntentQueue:{current:{invalidate:()=>Promise.resolve()}},previewMounted:{current:true},closingRef:{current:false},native:false,source:{...media},previewRegion:{start_frame:90,end_frame:240},previewJob:undefined,performance,Promise,
    fpsValue:r=>r.num/r.den,seconds:r=>r.num/r.den,endFrame:()=>300,
    document:{addEventListener(type,handler){assert.equal(type,'keydown');listeners.add(handler);},removeEventListener(type,handler){listeners.delete(handler);}},
    pause(){s.shuttle=0;events.push(['program-pause']);},pauseSource(){s.sourceShuttle=0;events.push(['source-pause']);},setShuttle(value){s.shuttle=typeof value==='function'?value(s.shuttle):value;events.push(['program-shuttle',s.shuttle]);},setSourceShuttle(value){s.sourceShuttle=typeof value==='function'?value(s.sourceShuttle):value;events.push(['source-shuttle',s.sourceShuttle]);},seek(frame){events.push(['program-seek',frame]);},edit(command){events.push(['edit',plain(command)]);return Promise.resolve();},observeProgram(){events.push(['observe']);},publishPlaybackAssets(){events.push(['publish-assets']);},report(error){events.push(['error',String(error)]);},invoke:()=>Promise.resolve('source-prepared'),
    saveProject(){events.push(['save']);},requestReplacement(){},importMedia(){},history(){},openMarker(){},convertFileSrc:x=>'asset://'+x,trackProgramFrame(frame){s.frame=frame;s.frameRef.current=frame;},
  };
  for(const [setter,field] of Object.entries({setMonitorTarget:'monitorTarget',setMonitorTab:'monitorTab',setMode:'mode',setSourceId:'sourceId',setSourcePath:'sourcePath',setSourceBusy:'sourceBusy',setSourceFrame:'sourceFrame',setSourceIn:'sourceIn',setSourceOut:'sourceOut',setProject:'project',setSelected:'selected',setDirty:'dirty',setRecordShortcut:'recordShortcut',setShortcuts:'shortcuts'}))s[setter]=value=>{s[field]=typeof value==='function'?value(s[field]):value;if(field==='sourceFrame')s.sourceFrameRef.current=s[field];events.push([setter,plain(s[field])]);};
  s.dirtyRef={current:false};vm.createContext(s);vm.runInContext(actualApp,s);s.sourceSelection.current.identity=s.actual.sourceIdentity(media);s.shortcuts={...s.actual.defaults};s.editorShortcutAllowed=require(join(build,'editorShortcuts.js')).editorShortcutAllowed;
  let cleanup=s.actual.install();
  function key(key,options={}){const event={key,code:key===' '?'Space':key,ctrlKey:false,altKey:false,shiftKey:false,metaKey:false,defaultPrevented:false,isComposing:false,target:new Target(),preventDefault(){this.defaultPrevented=true;},...options};for(const listener of listeners)listener(event);return event;}
  return {s,events,key,listeners,reinstall(){cleanup();cleanup=s.actual.install();},clear(){events.length=0;},monitor(target){return monitor(s.actual.props()[target]);}};
}
function monitor(props){const sandbox={exports:{},Element:Target,URL,document:{baseURI:'https://controlled.invalid/'},performance,require(name){if(name==='react')return {useRef:x=>({current:x}),useState:x=>[x,()=>{}],useEffect(){}};if(name==='react/jsx-runtime')return {jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})};if(name==='lucide-react')return new Proxy({},{get:(_,name)=>name});if(name==='./ui')return {IconButton:'IconButton'};if(name==='./ProgramMedia')return {default:'ProgramMedia'};if(name==='./types'||name==='./previewRegion'||name==='./monitorLifecycle')return require(join(build,name.slice(2)+'.js'));throw Error(name);}};vm.runInNewContext(readFileSync(join(build,'Monitor.js'),'utf8'),sandbox);return sandbox.exports.default(props);}
const actionNode=(tree,label)=>collect(tree,node=>node.props.label===label||node.props['aria-label']===label)[0];
test('actual Advanced/Easy monitor focus bindings route all seven keys to Source without sequence edits',()=>{
  for(const mode of ['easy','advanced'])for(const key of [' ','j','l','ArrowLeft','ArrowRight','i','o']){const h=harness(mode);h.monitor('source').props.onFocusCapture();h.clear();h.key(key);assert.equal(h.s.monitorTarget,'source');assert.ok(h.events.length);assert.ok(h.events.every(e=>!['program-pause','program-seek','program-shuttle','edit'].includes(e[0])));if(key==='i')assert.equal(h.s.sourceIn,42);if(key==='o')assert.equal(h.s.sourceOut,42);}
});
test('actual Program pointer binding marks global frame 120 despite preview origin 90 and source frame 42',()=>{
  for(const mode of ['easy','advanced']){const h=harness(mode);h.s.actual.activateMonitor('source');let focused=0;h.monitor('program').props.onPointerDownCapture({target:new Target('video'),currentTarget:{focus(){focused++;}}});assert.equal(focused,1);h.clear();h.key('i');h.key('o');assert.deepEqual(h.events,[['edit',{type:'set_range',in_point:120,out_point:200}],['edit',{type:'set_range',in_point:10,out_point:120}]]);assert.equal(h.s.sourceIn,0);assert.equal(h.s.sourceOut,null);h.key('ArrowRight');assert.ok(h.events.some(e=>e[0]==='program-seek'&&e[1]===121));}
});
test('source stepping executes actual stepSource with source fps, and Program stepping uses latest global frame ref',()=>{const h=harness();h.s.actual.activateMonitor('source');h.key('ArrowRight');assert.equal(h.s.sourceFrame,43);assert.equal(h.s.sourceVideo.current.currentTime,43/(24000/1001));h.s.actual.activateMonitor('program');h.s.frameRef.current=155;h.key('ArrowLeft');assert.deepEqual(h.events.at(-1),['program-seek',154]);});
test('J/L escalation and Space pause/resume affect selected transport only; K deliberately stops both',()=>{
  for(const target of ['source','program']){const h=harness();h.s.actual.activateMonitor(target);h.clear();for(const expected of [1,2,4,4]){h.key('l');assert.equal(h.s[target==='source'?'sourceShuttle':'shuttle'],expected);}for(const expected of [-1,-2,-4,-4]){h.key('j');assert.equal(h.s[target==='source'?'sourceShuttle':'shuttle'],expected);}h.key(' ');assert.equal(h.s[target==='source'?'sourceShuttle':'shuttle'],0);h.key(' ');assert.equal(h.s[target==='source'?'sourceShuttle':'shuttle'],1);assert.ok(h.events.every(e=>e[0].startsWith(target)));h.key('k');assert.equal(h.s.shuttle,0);assert.equal(h.s.sourceShuttle,0);}
});
test('Source remains usable when Program is dirty; Program playback cannot start on dirty or unplayable still regions',()=>{const h=harness();h.s.previewDirty=true;h.s.previewPlayable=false;h.s.actual.activateMonitor('source');h.clear();h.key('l');h.key('i');assert.equal(h.s.sourceShuttle,1);assert.equal(h.s.sourceIn,42);h.s.actual.activateMonitor('program');h.clear();for(const key of [' ','j','l'])h.key(key);assert.deepEqual(h.events,[]);h.s.previewDirty=false;h.clear();for(const key of [' ','j','l'])h.key(key);assert.deepEqual(h.events,[]);h.key('i');assert.equal(h.events[0][0],'edit');});
test('actual Easy tab and mode select bindings mirror target, mode changes choose Program',()=>{const h=harness('easy');h.s.actual.tabs[0]();assert.equal(h.s.monitorTarget,'source');assert.equal(h.s.monitorTab,'source');h.s.actual.tabs[1]();assert.equal(h.s.monitorTarget,'program');h.s.actual.activateMonitor('source');h.s.actual.modeChange({target:{value:'advanced'}});assert.equal(h.s.mode,'advanced');assert.equal(h.s.monitorTarget,'program');assert.equal(h.s.monitorTab,'program');});
test('actual workspace capture selects Program for timeline descendants and retains target elsewhere',()=>{const h=harness();h.s.actual.activateMonitor('source');h.s.actual.activateWorkspace({target:new Target('button',{},new Target('section',{class:'timeline-panel'}))});assert.equal(h.s.monitorTarget,'program');h.s.actual.activateMonitor('source');h.s.actual.activateWorkspace({target:new Target('button',{class:'menu-trigger'})});assert.equal(h.s.monitorTarget,'source');});
test('controls activate intended monitor without stealing native control focus; direct buttons agree with keyboard',()=>{const h=harness();let focused=0;const tree=h.monitor('source');tree.props.onPointerDownCapture({target:new Target('svg',{},new Target('button')),currentTarget:{focus(){focused++;}}});assert.equal(focused,0);h.s.actual.activateMonitor('program');h.clear();actionNode(tree,'Set source in point').props.onClick();assert.equal(h.s.monitorTarget,'source');assert.equal(h.s.sourceIn,42);assert.equal(h.events.some(e=>e[0]==='edit'),false);h.clear();h.key(' ',{target:new Target('button')});assert.deepEqual(h.events,[]);actionNode(tree,'Play source').props.onClick();assert.equal(h.s.sourceShuttle,1);h.s.previewPath=null;h.s.previewDirty=true;const p=h.monitor('program');assert.equal(actionNode(p,'Set program in point').props.disabled,false);actionNode(p,'Set program in point').props.onClick();assert.equal(h.s.monitorTarget,'program');assert.equal(h.events.at(-1)[1].in_point,120);});
test('actual Monitor is keyboard reachable and active target is named and styled with existing tokens',()=>{const h=harness();h.s.actual.activateMonitor('source');const tree=h.monitor('source');assert.equal(tree.props.tabIndex,0);assert.equal(tree.props.role,'region');assert.match(tree.props['aria-label'],/keyboard target/);assert.match(tree.props.className,/monitor-active/);assert.equal(collect(tree,n=>n.props.className==='monitor-target')[0].props['aria-hidden'],false);assert.match(readFileSync(join(root,'src/styles.css'),'utf8'),/\.monitor-active \.monitor-header \{ box-shadow: inset 0 -2px var\(--focus\); \}/);});
test('editable fields, dialogs, menus and role widgets own keys, including remapped frame-step keys',()=>{const h=harness();h.s.actual.activateMonitor('source');for(const target of [new Target('input'),new Target('textarea'),new Target('select'),new Target('span',{},new Target('div',{contenteditable:'plaintext-only'})),new Target('button',{},new Target('div',{class:'menu'})),new Target('div',{role:'menuitem'},new Target('div',{role:'menu'})),new Target('dialog'),new Target('div',{role:'dialog'}),new Target('div',{role:'slider'}),new Target('div',{role:'combobox'}),new Target('div',{role:'listbox'}),new Target('div',{role:'spinbutton'})]){h.clear();for(const key of [' ','j','l','ArrowLeft','ArrowRight','i','o'])assert.equal(h.key(key,{target}).defaultPrevented,false);assert.deepEqual(h.events,[]);}h.s.shortcuts.previous='q';h.clear();h.key('q',{target:new Target('button',{},new Target('div',{class:'menu'}))});assert.deepEqual(h.events,[]);for(const role of ['tab','separator','button','checkbox','switch','menuitem']){h.clear();h.key('ArrowRight',{target:new Target('div',{role})});assert.deepEqual(h.events,[]);}h.s.modal='export';h.clear();h.key('l');assert.deepEqual(h.events,[]);});
test('defaultPrevented, composition and remapping recording never also run a transport action',()=>{const h=harness();h.s.actual.activateMonitor('source');h.clear();h.key('l',{defaultPrevented:true});h.key('l',{isComposing:true});assert.deepEqual(h.events,[]);h.s.recordShortcut='forward';h.s.modal='shortcuts';h.key('l',{defaultPrevented:true});assert.equal(h.s.recordShortcut,'forward');h.key('p');assert.equal(h.s.shortcuts.forward,'p');assert.equal(h.s.recordShortcut,null);assert.equal(h.events.some(e=>e[0].includes('shuttle')),false);h.s.modal=null;h.clear();h.key('l');assert.deepEqual(h.events,[]);h.key('p');assert.equal(h.s.sourceShuttle,1);});
test('original and remapped keys use same actual handler with no duplicate subscriptions',()=>{const h=harness();h.s.actual.activateMonitor('source');h.s.shortcuts.markIn='Ctrl+Shift+x';for(let i=0;i<5;i++)h.reinstall();assert.equal(h.listeners.size,1);h.clear();h.key('i');assert.deepEqual(h.events,[]);h.key('X',{ctrlKey:true,shiftKey:true});assert.deepEqual(h.events,[['setSourceIn',42]]);});
test('missing, preparing, absent and image Source never fall through to Program commands',()=>{for(const kind of ['missing','preparing','absent','image']){const h=harness();h.s.actual.activateMonitor('source');if(kind==='missing')h.s.project.media[0].missing=true;if(kind==='preparing')h.s.sourceBusy=true;if(kind==='absent')h.s.sourcePath=null;if(kind==='image')h.s.project.media[0].kind='image';h.clear();for(const key of [' ','j','l','ArrowLeft','ArrowRight','i','o'])h.key(key);assert.deepEqual(h.events,[]);const tree=h.monitor('source');assert.equal(actionNode(tree,'Play source').props.disabled,true);assert.equal(actionNode(tree,'Set source in point').props.disabled,true);}});
test('actual project replacement/relink/history invalidates stale source ownership and same-source edits retain it',()=>{for(const change of ['project','path','missing','deleted','kind','fps','timing']){const h=harness();h.s.actual.activateMonitor('source');const p=structuredClone(h.s.project);if(change==='project')p.id='other';if(change==='path')p.media[0].path='replacement.mov';if(change==='missing')p.media[0].missing=true;if(change==='deleted')p.media=[];if(change==='kind')p.media[0].kind='audio';if(change==='fps')p.media[0].fps=r(60);if(change==='timing')p.media[0].timing={origin:r(3)};h.s.actual.replaceProject(p);assert.equal(h.s.monitorTarget,'program');assert.equal(h.s.sourcePath,null);assert.equal(h.s.sourceSelection.current,null);}const h=harness();h.s.actual.activateMonitor('source');h.s.actual.replaceProject(structuredClone(h.s.project));assert.equal(h.s.monitorTarget,'source');assert.equal(h.s.sourcePath,'asset://source');});
test('actual source selection pauses old transports, targets the new asset and ignores superseded preparation',async()=>{const h=harness(),replies=[];h.s.invoke=()=>new Promise(resolve=>replies.push(resolve));const next={...h.s.project.media[0],id:'next',path:'next.mov'};h.s.project.media.push(next);const first=h.s.actual.selectSource(h.s.project.media[0]);for(let i=0;i<8;i++)await Promise.resolve();const second=h.s.actual.selectSource(next);for(let i=0;i<8;i++)await Promise.resolve();assert.equal(h.s.monitorTarget,'source');assert.equal(h.s.sourceBusy,true);assert.equal(h.s.sourcePath,null);h.clear();h.key('i');assert.deepEqual(h.events,[]);replies[0]('stale');await first;assert.equal(h.s.sourcePath,null);replies[1]('fresh');await second;assert.equal(h.s.sourcePath,'asset://fresh');assert.equal(h.s.sourceId,'next');assert.equal(h.s.sourceFrame,0);h.s.actual.resetSourceForProject();assert.equal(h.s.monitorTarget,'program');assert.equal(h.s.sourceSelection.current,null);});

test('actual Easy tab navigation owns arrows/Home/End, updates focus and blocks the global handler',()=>{const h=harness('easy');const list=find(app,n=>ts.isJsxOpeningElement(n)&&n.attributes.properties?.some(p=>p.name?.text==='role'&&p.initializer?.text==='tablist'));assert.equal(list.attributes.properties.find(p=>p.name?.text==='onKeyDown').initializer.expression.getText(source),'navigateMonitorTabs');for(const key of ['ArrowRight','ArrowLeft','Home','End']){let focused;const event={key,target:new Target('button',{'data-monitor-tab':'program'}),currentTarget:{querySelector(selector){return {focus(){focused=selector;}};}},defaultPrevented:false,preventDefault(){this.defaultPrevented=true;}};h.s.actual.navigateMonitorTabs(event);const expected=key==='End'?'program':'source';assert.equal(h.s.monitorTarget,expected);assert.equal(h.s.monitorTab,expected);assert.ok(focused.includes(expected));h.clear();h.key(key,{defaultPrevented:event.defaultPrevented});assert.deepEqual(h.events,[]);}for(const tab of Object.values(monitors))assert.ok(tab);});
test('actual root activation bindings are attached to the shell; Tab and an expanded menu keep keyboard ownership',()=>{const shell=find(app,n=>ts.isJsxOpeningElement(n)&&n.attributes.properties?.some(p=>p.name?.text==='className'&&p.initializer.getText(source).includes('app-shell')));for(const name of ['onFocusCapture','onPointerDownCapture'])assert.equal(shell.attributes.properties.find(p=>p.name?.text===name).initializer.expression.getText(source),'activateWorkspace');const h=harness();h.s.actual.activateMonitor('source');h.s.shortcuts.forward='Tab';h.clear();assert.equal(h.key('Tab').defaultPrevented,false);assert.deepEqual(h.events,[]);h.s.shortcuts.forward='l';h.key('l',{target:new Target('button',{'aria-expanded':'true'})});assert.deepEqual(h.events,[]);h.key('l',{target:new Target('button',{'aria-expanded':'false'})});assert.equal(h.s.sourceShuttle,1);});
