import { Diamond, SlidersHorizontal, Video, Volume2, Palette, Type, ChevronDown, Move, Clock3, ArrowLeftRight } from 'lucide-react';
import { useEffect, useId, useRef, useState } from 'react';
import { Field, NumberField, IconButton } from './ui';
import { timecode, type Clip, type Edit, type Project, type Keyframe, type Rational, type RetimeClipCommand } from './types';
import { retimeCommand } from './retime';

function SpeedField({ id, speed, disabledReason, edit }: { id: string; speed: Rational; disabledReason: string | null; edit: Edit }) {
  const value = speed.num / speed.den, messageId = useId();
  const [draft, setDraft] = useState(String(value)), [editing, setEditing] = useState(false), [pending, setPending] = useState(false), [error, setError] = useState<string | null>(null);
  const cancel = useRef(false), inFlight = useRef(false);
  useEffect(() => { if (!editing && !pending) setDraft(String(value)); }, [value, editing, pending]);
  useEffect(() => setError(null), [speed.num, speed.den, disabledReason]);
  function commit() {
    setEditing(false);
    if (cancel.current || disabledReason || inFlight.current) { cancel.current = false; setDraft(String(value)); return; }
    const result = retimeCommand(id, speed, draft);
    setError(result.error);
    if (!result.command) { setDraft(String(value)); return; }
    inFlight.current = true; setPending(true);
    const command: RetimeClipCommand = result.command;
    void edit(command).catch(reason => setError(String(reason))).finally(() => { inFlight.current = false; setPending(false); });
  }
  const message = error ?? disabledReason ?? (pending ? 'Applying speed…' : null);
  return <><Field label="Speed"><div className="number-wrap"><input type="text" inputMode="decimal" value={draft} disabled={!!disabledReason || pending} aria-invalid={error ? true : undefined} aria-describedby={message ? messageId : undefined} onFocus={() => setEditing(true)} onChange={event => { setDraft(event.target.value); setError(null); }} onBlur={commit} onKeyDown={event => { if (event.key === 'Enter') { event.preventDefault(); event.currentTarget.blur(); } if (event.key === 'Escape') { event.preventDefault(); cancel.current = true; event.currentTarget.blur(); } }} /><span>×</span></div></Field>{message && <p id={messageId} className="field-help" role={error ? 'alert' : pending ? 'status' : undefined}>{message}</p>}</>;
}

export default function Inspector({ project, selected, frame, edit, easy = false }: { project: Project; selected: string[]; frame: number; edit: Edit; easy?: boolean }) {
  const [tab, setTab] = useState('basic');
  const clip = project.clips.find(c => c.id === selected[0]); const media = project.media.find(m => m.id === clip?.media_id);
  const speedDisabled = clip?.title !== null && clip?.title !== undefined ? 'Titles have no playback speed. Change their length with Trim out.' : media?.kind === 'image' ? 'Still images have no playback speed. Change their length with Trim out.' : !media ? 'Relink this clip to video or audio before changing speed.' : project.tracks.find(track => track.id === clip?.track_id)?.locked ? 'Unlock this track before changing speed.' : null;
  const predecessor = clip && project.tracks.find(t => t.id === clip.track_id)?.kind === 'video' ? project.clips.filter(c => c.id !== clip.id && c.track_id === clip.track_id && c.start < clip.start).sort((a, b) => b.start - a.start)[0] : undefined;
  const maxDissolve = Math.max(1, Math.min(clip?.duration || 1, predecessor?.duration || 1)), [dissolveFrames, setDissolveFrames] = useState(15);
  useEffect(() => setDissolveFrames(Math.min(maxDissolve, Math.max(1, Math.round(project.fps.num / project.fps.den / 2)))), [clip?.id, predecessor?.id]);
  function patch(values: Record<string, unknown>) { if (clip) void edit({ type: 'update_clip', id: clip.id, patch: values }); }
  function localFrame() { return clip ? Math.max(0, Math.min(clip.duration - 1, frame - clip.start)) : 0; }
  function keyframe(property: Keyframe['property'], value: number) { if (!clip) return; const local = localFrame(); patch({ keyframes: [...clip.keyframes.filter(k => k.property !== property || k.frame !== local), { property, frame: local, value }] }); }
  function keyButton(property: Keyframe['property'], value: number) { const local = localFrame(); return <IconButton label={`Add ${property} keyframe at playhead`} active={clip?.keyframes.some(k => k.property === property && k.frame === local)} onClick={() => keyframe(property, value)}><Diamond size={13} /></IconButton>; }
  function number(label: string, property: keyof Clip, min: number, max: number, step = .01) { return <NumberField label={label} value={Number(clip?.[property] || 0)} min={min} max={max} step={step} onChange={v => patch({ [property]: v })} />; }
  function transform(label: string, property: keyof Clip['transform'], min: number, max: number, step = 1) { return <NumberField label={label} value={clip?.transform[property] || 0} min={min} max={max} step={step} onChange={v => patch({ transform: { ...clip?.transform, [property]: v } })} />; }
  return <aside data-tour="inspector" data-tab={tab} className={`inspector panel ${easy ? 'simple-inspector' : ''}`} aria-label="Clip inspector"><header className="panel-heading"><span><SlidersHorizontal size={15} />{easy ? 'Clip settings' : 'Inspector'}</span>{clip && <span className="badge">{selected.length > 1 ? `${selected.length} selected` : clip.title !== null ? 'Title' : media?.kind || 'Clip'}</span>}</header>{easy && <div className="inspector-tabs" role="tablist" aria-label="Clip property groups">{['basic', 'audio', 'speed', 'color'].map(name => <button key={name} role="tab" aria-selected={tab === name} onClick={() => setTab(name)}>{name[0].toUpperCase() + name.slice(1)}</button>)}</div>}
    {!clip ? <div className="inspector-empty"><SlidersHorizontal size={25} strokeWidth={1.3} /><strong>Select a clip</strong><p>Adjust its timing, picture and sound.</p></div> : <div className="inspector-scroll">
      <div className="clip-summary"><strong>{clip.name}</strong><span>{timecode(clip.start, project.fps)} <span className="secondary">→</span> {timecode(clip.start + clip.duration, project.fps)}</span>{selected.length > 1 && <p>Properties apply to the first selected clip. Speed also updates linked video and audio.</p>}</div>
      {clip.title !== null && <details data-section="basic" open className="inspector-section"><summary><Type size={14} />Title<ChevronDown size={13} /></summary><div className="section-fields"><Field label="Text"><textarea rows={3} value={clip.title} onChange={e => patch({ title: e.target.value, name: e.target.value.slice(0, 40) || 'Title' })} /></Field></div></details>}
      <details data-section="basic" open className="inspector-section"><summary><Move size={14} />Transform<ChevronDown size={13} /></summary><div className="section-fields">
        <div className="field-pair">{transform('Position X', 'x', -project.width * 2, project.width * 2)}{transform('Position Y', 'y', -project.height * 2, project.height * 2)}</div>
        <div className="keyframe-field">{transform('Scale', 'scale', .01, 20, .01)}{keyButton('scale', clip.transform.scale)}</div>{transform('Rotation', 'rotation', -360, 360)}
        <div className="keyframe-field">{number('Opacity', 'opacity', 0, 1)}{keyButton('opacity', clip.opacity)}</div>
        <button className="subtle-button" onClick={() => patch({ transform: { x: 0, y: 0, scale: 1, rotation: 0, crop_left: 0, crop_right: 0, crop_top: 0, crop_bottom: 0 }, opacity: 1 })}>Reset transform</button>
      </div></details>
      <details data-section="basic" open={easy || undefined} className="inspector-section"><summary><ArrowLeftRight size={14} />Cross dissolve<ChevronDown size={13} /></summary><div className="section-fields"><NumberField label="Duration" value={dissolveFrames} min={1} max={maxDissolve} suffix="frames" onChange={setDissolveFrames} /><button className="subtle-button" disabled={!predecessor || project.tracks.find(t => t.id === clip.track_id)?.locked} onClick={() => void edit({ type: 'cross_dissolve', id: clip.id, frames: Math.min(maxDissolve, Math.max(1, Math.round(dissolveFrames))) })}><ArrowLeftRight size={13} />Apply cross dissolve</button><p className="field-help">{predecessor ? `Dissolve from ${predecessor.name}. Moves this clip to overlap, with matched picture and audio fades.` : 'Select a clip after another on the same video track.'}</p></div></details>
      <details data-section="basic" className="inspector-section"><summary><Video size={14} />Crop<ChevronDown size={13} /></summary><div className="section-fields"><div className="field-pair">{transform('Left', 'crop_left', 0, .95, .01)}{transform('Right', 'crop_right', 0, .95, .01)}</div><div className="field-pair">{transform('Top', 'crop_top', 0, .95, .01)}{transform('Bottom', 'crop_bottom', 0, .95, .01)}</div><p className="field-help">Fraction of source picture, from 0 to 1.</p></div></details>
      <details data-section="speed" open={easy || undefined} className="inspector-section"><summary><Clock3 size={14} />Timing<ChevronDown size={13} /></summary><div className="section-fields"><NumberField label="Sequence start" value={clip.start} min={0} suffix="f" onChange={v => void edit({ type: 'move', ids: [clip.id], delta: Math.round(v) - clip.start })} /><Field label="Track"><select value={clip.track_id} onChange={e => void edit({ type: 'move', ids: [clip.id], delta: 0, track_id: e.target.value })}>{project.tracks.filter(t => t.kind === project.tracks.find(t => t.id === clip.track_id)?.kind && !t.locked).map(t => <option value={t.id} key={t.id}>{t.name}</option>)}</select></Field><div className="field-pair"><NumberField label="Trim in at" value={clip.start} min={0} suffix="f" onChange={v => void edit({ type: 'trim', id: clip.id, edge: 'in', frame: Math.round(v) })} /><NumberField label="Trim out at" value={clip.start + clip.duration} min={clip.start + 1} suffix="f" onChange={v => void edit({ type: 'trim', id: clip.id, edge: 'out', frame: Math.round(v) })} /></div><SpeedField key={clip.id} id={clip.id} speed={clip.speed} disabledReason={speedDisabled} edit={edit} /><Field label="Duration"><input readOnly value={`${clip.duration} frames · ${timecode(clip.duration, project.fps)}`} /></Field><NumberField label="Slip source" value={0} step={1} suffix="frames" onChange={v => void edit({ type: 'slip', id: clip.id, delta: Math.round(v) })} /><div className="field-pair"><NumberField label="Fade in" value={clip.fade_in} min={0} max={clip.duration} suffix="f" onChange={v => patch({ fade_in: Math.round(v) })} /><NumberField label="Fade out" value={clip.fade_out} min={0} max={clip.duration} suffix="f" onChange={v => patch({ fade_out: Math.round(v) })} /></div>{(clip.fade_in_start != null || clip.fade_out_end != null) && <p className="field-help">Fades keep their timing after a cut or trim. Changing a fade anchors it to this clip’s edge.</p>}<p className="field-help">Audio pitch changes with speed.</p><p className="field-help">Overlap clips and use fades for a cross dissolve.</p></div></details>
      <details data-section="audio" open className="inspector-section"><summary><Volume2 size={14} />Audio<ChevronDown size={13} /></summary><div className="section-fields"><div className="keyframe-field">{number('Volume', 'volume', 0, 4, .05)}{keyButton('volume', clip.volume)}</div><div className="audio-meter-label"><span>{clip.volume === 0 ? 'Muted' : `${(20 * Math.log10(clip.volume)).toFixed(1)} dB`}</span><button className="text-button" onClick={() => patch({ volume: 1 })}>Reset</button></div></div></details>
      <details data-section="color" open={easy || undefined} className="inspector-section"><summary><Palette size={14} />Color<ChevronDown size={13} /></summary><div className="section-fields">{number('Brightness', 'brightness', -1, 1)}{number('Contrast', 'contrast', 0, 3)}{number('Saturation', 'saturation', 0, 3)}<button className="subtle-button" onClick={() => patch({ brightness: 0, contrast: 1, saturation: 1 })}>Reset color</button></div></details>
      <details data-section="advanced" className="inspector-section"><summary><Diamond size={14} />Keyframes<span className="count">{clip.keyframes.length}</span><ChevronDown size={13} /></summary><div className="section-fields"><div className="field-pair"><button className="subtle-button" onClick={() => keyframe('x', clip.transform.x)}>Key position X</button><button className="subtle-button" onClick={() => keyframe('y', clip.transform.y)}>Key position Y</button></div>{clip.keyframes.length === 0 ? <p className="field-help">Use a diamond to set a value at the playhead. Values interpolate between keyframes.</p> : <div className="keyframe-list">{clip.keyframes.slice().sort((a, b) => a.frame - b.frame).map((k, i) => <div key={`${k.property}-${k.frame}-${i}`}><span>{k.property} <span className="secondary">· {k.frame}f{k.frame === clip.duration ? ' · out' : ''}</span></span><span>{k.value.toFixed(2)}</span><button aria-label={`Remove ${k.property} keyframe at ${k.frame}`} onClick={() => patch({ keyframes: clip.keyframes.filter(other => other !== k) })}>×</button></div>)}</div>}</div></details>
      <details data-section="advanced" className="inspector-section"><summary><Video size={14} />Source<ChevronDown size={13} /></summary><div className="source-details">{media ? <><span>{media.width} × {media.height}</span><span>{media.fps.num}/{media.fps.den} fps</span><span>{media.has_audio ? 'Audio included' : 'No audio'}</span><span>Source in: {(clip.source_in.num / clip.source_in.den).toFixed(4)} s</span><span className="path-text" title={media.path}>{media.path}</span></> : <span>Generated title · Inter</span>}</div></details>
    </div>}
  </aside>;
}
